import type { HelperUser, HelpRequest, Conversation, Review, FamilyUser, Category, ServiceType } from './types';

export const CATEGORY_LABELS: Record<string, string> = {
  grocery: 'Купити продукти',
  pharmacy: 'Забрати ліки',
  household: 'Допомогти по дому',
  walk: 'Сходити на прогулянку',
  companionship: 'Скласти компанію',
  documents: 'Допомогти з документами',
  transport: 'Супроводити кудись',
  cooking: 'Приготувати їжу',
  delivery: 'Доставка',
  other: 'Інше',
  care: 'Професійний догляд',
  medical: 'Медичні процедури',
  rehab: 'Реабілітаційна допомога',
};

export const CATEGORY_SERVICE_TYPE: Record<Category, ServiceType> = {
  grocery: 'basic',
  pharmacy: 'basic',
  household: 'basic',
  walk: 'basic',
  companionship: 'basic',
  documents: 'basic',
  transport: 'basic',
  cooking: 'basic',
  delivery: 'basic',
  other: 'basic',
  care: 'specialized',
  medical: 'specialized',
  rehab: 'specialized',
};

export const BASIC_CATEGORIES: Category[] = [
  'grocery', 'pharmacy', 'household', 'walk', 'companionship',
  'documents', 'transport', 'cooking', 'delivery', 'other',
];

export const SPECIALIZED_CATEGORIES: Category[] = ['care', 'medical', 'rehab'];

export const RELATIONSHIP_LABELS: Record<string, string> = {
  mother: 'Мама',
  father: 'Тато',
  grandmother: 'Бабуся',
  grandfather: 'Дідусь',
  other: 'Інший родич',
};

export const demoFamilyUser: FamilyUser = {
  id: 'f1',
  name: 'Ганна',
  phone: '+380 67 123 45 67',
  email: 'anna@example.com',
  relative: {
    id: 'e1',
    name: 'Марія',
    age: 74,
    city: 'Суми',
    address: 'вул. Троїцька, 15, кв. 23',
    phone: '+380 50 987 65 43',
    relationship: 'mother',
  },
};

export const demoHelpers: HelperUser[] = [
  {
    id: 'h1',
    name: 'Олена К.',
    phone: '+380 67 555 11 22',
    email: 'olena@example.com',
    photo: '',
    rating: 4.9,
    completedTasks: 48,
    verified: true,
    trained: true,
    bio: 'Студентка, живе поруч і допомагає літнім людям з продуктами та господарськими справами.',
    distanceKm: 1.2,
    available: true,
    specialties: ['grocery', 'household', 'delivery', 'walk'],
    qualifications: [],
    qualified: false,
  },
  {
    id: 'h2',
    name: 'Андрій П.',
    phone: '+380 96 333 44 55',
    email: 'andriy@example.com',
    photo: '',
    rating: 4.8,
    completedTasks: 32,
    verified: true,
    trained: true,
    bio: 'Волонтер з досвідом. Маю авто, допомагаю з транспортом та документами.',
    distanceKm: 2.5,
    available: true,
    specialties: ['transport', 'grocery', 'documents', 'pharmacy'],
    qualifications: [],
    qualified: false,
  },
  {
    id: 'h3',
    name: 'Наталія В.',
    phone: '+380 73 777 88 99',
    email: 'natalia@example.com',
    photo: '',
    rating: 5.0,
    completedTasks: 67,
    verified: true,
    trained: true,
    bio: 'Соціальна працівниця з 5-річним досвідом. Спеціалізуюсь на догляді та компанії.',
    distanceKm: 3.1,
    available: true,
    specialties: ['walk', 'companionship', 'household', 'care', 'cooking'],
    qualifications: ['Медична сестра', 'Курси догляду'],
    qualified: true,
  },
  {
    id: 'h4',
    name: 'Тарас М.',
    phone: '+380 67 111 22 33',
    email: 'taras@example.com',
    photo: '',
    rating: 4.7,
    completedTasks: 21,
    verified: true,
    trained: true,
    bio: 'Допомагаю по дому з технічними справами та дрібним ремонтом.',
    distanceKm: 4.0,
    available: false,
    specialties: ['household', 'transport', 'documents'],
    qualifications: [],
    qualified: false,
  },
  {
    id: 'h5',
    name: 'Софія Р.',
    phone: '+380 50 444 55 66',
    email: 'sofia@example.com',
    photo: '',
    rating: 4.9,
    completedTasks: 55,
    verified: true,
    trained: true,
    bio: 'Медсестра на пенсії. Маю медичну освіту, можу супроводжувати до лікаря та допомагати з ліками.',
    distanceKm: 1.8,
    available: true,
    specialties: ['pharmacy', 'transport', 'walk', 'care', 'medical'],
    qualifications: ['Медична сестра', 'Перша допомога'],
    qualified: true,
  },
];

export const demoRequests: HelpRequest[] = [
  {
    id: 'r1',
    category: 'grocery',
    description: 'Купити продукти за списком та доставити бабусі додому.',
    date: '2026-10-04',
    time: '16:00',
    address: 'вул. Троїцька, 15, кв. 23',
    approximateArea: 'Центральний район, Суми',
    duration: '1 год',
    reward: 250,
    elderlyName: 'Марія',
    elderlyAge: 74,
    elderlyCity: 'Суми',
    distanceKm: 1.2,
    status: 'accepted',
    serviceType: 'basic',
    helperId: 'h1',
    shoppingList: ['Молоко', 'Хліб', 'Яблука', 'Ліки від тиску'],
    createdAt: '2026-10-04T10:00:00',
  },
  {
    id: 'r2',
    category: 'pharmacy',
    description: 'Забрати ліки з аптеки та принести додому.',
    date: '2026-10-02',
    time: '11:00',
    address: 'вул. Троїцька, 15, кв. 23',
    approximateArea: 'Центральний район, Суми',
    duration: '30 хв',
    reward: 200,
    elderlyName: 'Марія',
    elderlyAge: 74,
    elderlyCity: 'Суми',
    distanceKm: 1.2,
    status: 'reviewed',
    serviceType: 'basic',
    helperId: 'h5',
    helperNote: 'Ліки доставлені вчасно. Бабуся почувається добре.',
    createdAt: '2026-10-02T09:00:00',
  },
  {
    id: 'r3',
    category: 'walk',
    description: 'Скласти компанію на прогулянці в парку.',
    date: '2026-09-28',
    time: '15:00',
    address: 'Парк ім. Шевченка, Суми',
    approximateArea: 'Парк ім. Шевченка, Суми',
    duration: '1.5 год',
    reward: 300,
    elderlyName: 'Марія',
    elderlyAge: 74,
    elderlyCity: 'Суми',
    distanceKm: 1.5,
    status: 'reviewed',
    serviceType: 'basic',
    helperId: 'h3',
    helperNote: 'Чудова прогулянка, бабуся дуже задоволена!',
    createdAt: '2026-09-28T10:00:00',
  },
];

export const demoAvailableRequests: HelpRequest[] = [
  {
    id: 'ar1',
    category: 'grocery',
    description: 'Купити продукти за списком та доставити додому.',
    date: '2026-10-04',
    time: '16:00',
    address: 'вул. Троїцька, 15',
    approximateArea: 'Центральний район, Суми',
    duration: '1 год',
    reward: 250,
    elderlyName: 'Марія',
    elderlyAge: 74,
    elderlyCity: 'Суми',
    distanceKm: 1.2,
    status: 'searching',
    serviceType: 'basic',
    shoppingList: ['Молоко', 'Хліб', 'Яблука', 'Ліки від тиску'],
    createdAt: '2026-10-04T10:00:00',
  },
  {
    id: 'ar2',
    category: 'companionship',
    description: 'Скласти компанію на прогулянці в парку. Бабусі потрібен супровід.',
    date: '2026-10-05',
    time: '10:00',
    address: 'вул. Кооперативна, 8',
    approximateArea: 'Зарічний район, Суми',
    duration: '1.5 год',
    reward: 300,
    elderlyName: 'Галина',
    elderlyAge: 81,
    elderlyCity: 'Суми',
    distanceKm: 0.8,
    status: 'searching',
    serviceType: 'basic',
    createdAt: '2026-10-04T08:00:00',
  },
  {
    id: 'ar3',
    category: 'household',
    description: 'Допомогти прибрати вдома та винести сміття.',
    date: '2026-10-06',
    time: '14:00',
    address: 'вул. Харківська, 22',
    approximateArea: 'Харківський район, Суми',
    duration: '2 год',
    reward: 400,
    elderlyName: 'Олексій',
    elderlyAge: 79,
    elderlyCity: 'Суми',
    distanceKm: 2.1,
    status: 'searching',
    serviceType: 'basic',
    createdAt: '2026-10-04T09:00:00',
  },
  {
    id: 'ar4',
    category: 'care',
    description: 'Потрібен професійний догляд за лежачим хворим. Перев'язки та контроль ліків.',
    date: '2026-10-05',
    time: '09:00',
    address: 'вул. Київська, 45',
    approximateArea: 'Київський район, Суми',
    duration: '3 год',
    reward: 600,
    elderlyName: 'Наталія',
    elderlyAge: 82,
    elderlyCity: 'Суми',
    distanceKm: 3.5,
    status: 'searching',
    serviceType: 'specialized',
    createdAt: '2026-10-04T07:00:00',
  },
  {
    id: 'ar5',
    category: 'delivery',
    description: 'Забрати посилку з Нова Пошта та доставити додому.',
    date: '2026-10-04',
    time: '12:00',
    address: 'вул. Вокзальна, 3',
    approximateArea: 'Зарічний район, Суми',
    duration: '30 хв',
    reward: 150,
    elderlyName: 'Андрій',
    elderlyAge: 76,
    elderlyCity: 'Суми',
    distanceKm: 1.5,
    status: 'searching',
    serviceType: 'basic',
    createdAt: '2026-10-04T06:00:00',
  },
];

export const demoHelperActiveRequests: HelpRequest[] = [
  {
    id: 'hr1',
    category: 'grocery',
    description: 'Купити продукти за списком та доставити додому.',
    date: '2026-10-04',
    time: '16:00',
    address: 'вул. Троїцька, 15, кв. 23',
    approximateArea: 'Центральний район, Суми',
    duration: '1 год',
    reward: 250,
    elderlyName: 'Марія',
    elderlyAge: 74,
    elderlyCity: 'Суми',
    distanceKm: 1.2,
    status: 'accepted',
    serviceType: 'basic',
    helperId: 'h1',
    shoppingList: ['Молоко', 'Хліб', 'Яблука', 'Ліки від тиску'],
    createdAt: '2026-10-04T10:00:00',
  },
];

export const demoReviews: Review[] = [
  {
    id: 'rv1',
    requestId: 'r2',
    rating: 5,
    comment: 'Софія дуже турботлива. Доставила ліки швидко, бабуся дуже задоволена!',
    authorName: 'Ганна',
    createdAt: '2026-10-02',
  },
  {
    id: 'rv2',
    requestId: 'r3',
    rating: 5,
    comment: 'Наталія чудово склала компанію. Дякуємо!',
    authorName: 'Ганна',
    createdAt: '2026-09-28',
  },
];

export const demoConversations: Conversation[] = [
  {
    id: 'c1',
    personName: 'Олена К.',
    personAvatar: '',
    lastMessage: 'Добрий день! Я взяла ваше замовлення, буду о 16:00.',
    lastTimestamp: '14:32',
    unread: 2,
    messages: [
      {
        id: 'm1',
        senderId: 'h1',
        senderName: 'Олена К.',
        text: 'Добрий день, Ганно! Я побачила ваше замовлення на продукти.',
        timestamp: '14:30',
        isOwn: false,
      },
      {
        id: 'm2',
        senderId: 'h1',
        senderName: 'Олена К.',
        text: 'Добрий день! Я взяла ваше замовлення, буду о 16:00.',
        timestamp: '14:32',
        isOwn: false,
      },
    ],
  },
  {
    id: 'c2',
    personName: 'Софія Р.',
    personAvatar: '',
    lastMessage: 'Ліки доставлені. Бажаю здоров\'я!',
    lastTimestamp: 'Вчора',
    unread: 0,
    messages: [
      {
        id: 'm3',
        senderId: 'h5',
        senderName: 'Софія Р.',
        text: 'Ліки доставлені. Бажаю здоров\'я!',
        timestamp: '11:45',
        isOwn: false,
      },
    ],
  },
];

export const demoHelperConversations: Conversation[] = [
  {
    id: 'hc1',
    personName: 'Ганна (родина Марії)',
    personAvatar: '',
    lastMessage: 'Дякую! Бабуся буде дуже вдячна.',
    lastTimestamp: '14:35',
    unread: 1,
    messages: [
      {
        id: 'hm1',
        senderId: 'f1',
        senderName: 'Ганна',
        text: 'Добрий день! Дякую, що взяли замовлення.',
        timestamp: '14:33',
        isOwn: false,
      },
      {
        id: 'hm2',
        senderId: 'f1',
        senderName: 'Ганна',
        text: 'Дякую! Бабуся буде дуже вдячна.',
        timestamp: '14:35',
        isOwn: false,
      },
    ],
  },
];
